# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['launcher.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('core', 'core'),
        ('radiogeet_axionix', 'radiogeet_axionix'),
        ('db.sqlite3', '.'),
    ],
    hiddenimports=[
        # ---- pywebview 6.x ----
        'webview',
        'webview.http',
        'webview.guilib',
        'webview.util',
        'webview.event',
        'webview.dom',
        'webview.platforms',
        'webview.platforms.winforms',
        'webview.platforms.edgechromium',
        'webview.platforms.mshtml',
        'webview.platforms.cef',
        'bottle',
        'proxy_tools',
        'pythonnet',
        'clr_loader',
        # ---- pystray ----
        'pystray',
        'pystray._base',
        'pystray._win32',
        # ---- PIL / Pillow ----
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.BmpImagePlugin',
        'PIL.PngImagePlugin',
        'PIL.IcoImagePlugin',
        'PIL.JpegImagePlugin',
        # ---- Django ----
        'django.contrib.staticfiles',
        'django.contrib.auth',
        'django.contrib.auth.backends',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.sessions.backends.db',
        'django.contrib.messages',
        'django.contrib.messages.storage.fallback',
        'django.db.backends.sqlite3',
        'django.template.loaders.filesystem',
        'django.template.loaders.app_directories',
        'django.template.context_processors',
        # ---- Modbus / Serial ----
        'minimalmodbus',
        'serial',
        'serial.tools',
        'serial.tools.list_ports',
        'serial.tools.list_ports_windows',
        'serial.serialutil',
        'serial.serialposix',
        'serial.serialwin32',
        # ---- Core app ----
        'core',
        'core.models',
        'core.views',
        'core.urls',
        'core.admin',
        'core.apps',
        'core.modbus_daemon',
        # ---- ReportLab (PDF) ----
        'reportlab',
        'reportlab.lib',
        'reportlab.lib.pagesizes',
        'reportlab.lib.units',
        'reportlab.lib.colors',
        'reportlab.lib.styles',
        'reportlab.lib.enums',
        'reportlab.pdfgen',
        'reportlab.pdfgen.canvas',
        'reportlab.platypus',
        'reportlab.platypus.tables',
        'reportlab.platypus.paragraph',
        'reportlab.platypus.doctemplate',
        'reportlab.graphics',
        # ---- openpyxl (Excel) ----
        'openpyxl',
        'openpyxl.workbook',
        'openpyxl.styles',
        'openpyxl.utils',
        # ---- Other ----
        'struct',
        'threading',
        'socket',
        'core.forms',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'IPython',
        'notebook',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='RadiogeetAXIONIX',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='static/images/icon2.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='RadiogeetAXIONIX',
)
