# Generated by Django 6.0.6 on 2026-07-04 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity_kl', models.FloatField(default=5.0)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=200)),
                ('industry_type', models.CharField(choices=[('oil_gas', 'Oil & Gas'), ('petrochemical', 'Petrochemical'), ('pharmaceutical', 'Pharmaceutical'), ('water_treatment', 'Water Treatment'), ('power_generation', 'Power Generation'), ('food_beverage', 'Food & Beverage'), ('chemical', 'Chemical Processing'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('language', models.CharField(default='English', max_length=20)),
                ('activation_key', models.CharField(blank=True, max_length=100)),
                ('is_activated', models.BooleanField(default=False)),
                ('system_usage', models.CharField(blank=True, max_length=50)),
                ('number_of_sites', models.IntegerField(default=1)),
                ('preferred_storage', models.CharField(choices=[('local', 'Local Storage'), ('cloud', 'Cloud Storage'), ('hybrid', 'Hybrid (Local + Cloud)')], default='local', max_length=20)),
                ('units_preference', models.CharField(choices=[('metric', 'Metric (KL, °C, bar)'), ('imperial', 'Imperial (gal, °F, psi)')], default='metric', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(choices=[('high', 'High Alarm'), ('low', 'Low Alarm')], max_length=10)),
                ('level_percent', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='core.tank')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TankReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_percent', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.tank')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('operator', 'Operator'), ('engineer', 'Engineer'), ('manager', 'Plant Manager'), ('supervisor', 'Supervisor'), ('viewer', 'Viewer')], default='operator', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
