# Generated by Django 6.0.6 on 2026-07-04 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_can_view_alarms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_view_alarms',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_view_dashboard',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_view_datalog',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_view_events',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_view_reports',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_view_settings',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_view_trend',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_view_users',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_app_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_group',
            field=models.CharField(blank=True, choices=[('operations', 'Operations Team'), ('admin_team', 'Admin Team'), ('engineering', 'Engineering Team'), ('management', 'Management'), ('maintenance', 'Maintenance Team')], default='operations', max_length=50),
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('can_view', models.BooleanField(default=True)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'module_name')},
            },
        ),
    ]
