# Generated by Django 6.0.6 on 2026-07-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userprofile_can_view_alarms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_tanks',
            field=models.ManyToManyField(blank=True, related_name='assigned_profiles', to='core.tank'),
        ),
    ]
