# Generated by Django 6.0.6 on 2026-07-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_assigned_tanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='high_limit',
            field=models.FloatField(default=90.0),
        ),
        migrations.AddField(
            model_name='tank',
            name='low_limit',
            field=models.FloatField(default=10.0),
        ),
    ]
