# Generated by Django 6.0.6 on 2026-07-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tank_high_limit_tank_low_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialConnectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(default='Masibus Scanner 01', max_length=100)),
                ('device_type', models.CharField(default='Masibus Scanner', max_length=100)),
                ('connection_type', models.CharField(default='Serial (RS485)', max_length=50)),
                ('com_port', models.CharField(default='COM3', max_length=20)),
                ('baud_rate', models.IntegerField(default=9600)),
                ('data_bits', models.IntegerField(default=8)),
                ('parity', models.CharField(default='None', max_length=10)),
                ('stop_bits', models.IntegerField(default=1)),
                ('slave_id', models.IntegerField(default=1)),
            ],
        ),
    ]
