# Generated by Django 6.0.6 on 2026-07-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_serialconnectionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='register_address',
            field=models.IntegerField(default=40001),
        ),
    ]
