# Generated by Django 6.0.6 on 2026-07-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tank_register_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_address', models.IntegerField(unique=True)),
                ('value', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='tank',
            name='widget_type',
            field=models.CharField(default='cylinder', max_length=20),
        ),
    ]
