# Generated by Django 6.0.6 on 2026-07-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_simulatedregister_tank_widget_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModbusDiagnosticStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_packets', models.IntegerField(default=0)),
                ('rx_packets', models.IntegerField(default=0)),
                ('crc_errors', models.IntegerField(default=0)),
                ('timeout_count', models.IntegerField(default=0)),
                ('response_time_ms', models.FloatField(default=0.0)),
                ('comm_quality', models.FloatField(default=100.0)),
                ('last_comm', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModbusFrameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('direction', models.CharField(max_length=5)),
                ('frame_hex', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='serialconnectionconfig',
            name='auto_reconnect',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serialconnectionconfig',
            name='polling_interval',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='serialconnectionconfig',
            name='response_delay',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='serialconnectionconfig',
            name='retry_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='serialconnectionconfig',
            name='rts_delay',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='serialconnectionconfig',
            name='timeout',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='tank',
            name='byte_order',
            field=models.CharField(default='ABCD', max_length=10),
        ),
        migrations.AddField(
            model_name='tank',
            name='data_type',
            field=models.CharField(default='UInt16', max_length=20),
        ),
        migrations.AddField(
            model_name='tank',
            name='function_code',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tank',
            name='offset',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tank',
            name='scaling',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='tank',
            name='slave_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tank',
            name='unit',
            field=models.CharField(default='%', max_length=10),
        ),
    ]
