# Generated by Django 6.0.6 on 2026-07-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_modbusdiagnosticstats_modbusframelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='raw_span',
            field=models.FloatField(default=20000.0),
        ),
        migrations.AddField(
            model_name='tank',
            name='raw_zero',
            field=models.FloatField(default=4000.0),
        ),
        migrations.AlterField(
            model_name='serialconnectionconfig',
            name='timeout',
            field=models.FloatField(default=1.0),
        ),
    ]
