# Generated by Django 6.0.6 on 2026-07-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tank_raw_span_tank_raw_zero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialconnectionconfig',
            name='polling_interval',
            field=models.FloatField(default=5.0),
        ),
    ]
