# Generated by Django 6.0.6 on 2026-07-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_serialconnectionconfig_polling_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanks', to='core.serialconnectionconfig'),
        ),
    ]
