# Generated by Django 6.0.6 on 2026-07-17 13:05

import django.db.models.deletion
from django.db import migrations, models


def clear_serial_config(apps, schema_editor):
    SerialConnectionConfig = apps.get_model('core', 'SerialConnectionConfig')
    SerialConnectionConfig.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tank_connection'),
    ]

    operations = [
        migrations.RunPython(clear_serial_config),
        migrations.CreateModel(
            name='FlowMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('slave_id', models.IntegerField(default=1)),
                ('flow_rate_register', models.IntegerField(default=40001)),
                ('total_volume_register', models.IntegerField(default=40003)),
                ('function_code', models.IntegerField(default=3)),
                ('data_type', models.CharField(default='Float32', max_length=20)),
                ('byte_order', models.CharField(default='ABCD', max_length=10)),
                ('flow_unit', models.CharField(default='L/min', max_length=20)),
                ('total_unit', models.CharField(default='Liters', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='tank',
            name='connection',
        ),
        migrations.AddField(
            model_name='serialconnectionconfig',
            name='profile_name',
            field=models.CharField(default='Tanks', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='FlowMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_rate', models.FloatField(default=0.0)),
                ('total_volume', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flow_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.flowmeter')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
