# Generated by Django 6.0.6 on 2026-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_flowmeter_remove_tank_connection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(default='3-Day Lifetime Trial License', max_length=50)),
                ('license_key', models.CharField(default='RADIOGEET-AXIONIX-S3CR3T-K3Y-2026-3T', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
