# Generated by Django 6.0.6 on 2026-07-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_licenseconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='raw_span',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tank',
            name='raw_zero',
            field=models.FloatField(default=0.0),
        ),
    ]
