# Generated by Django 6.0.6 on 2026-07-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_tank_raw_span_alter_tank_raw_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='raw_span',
            field=models.FloatField(default=20000.0),
        ),
        migrations.AlterField(
            model_name='tank',
            name='raw_zero',
            field=models.FloatField(default=4000.0),
        ),
    ]
