# Generated by Django 6.0.6 on 2026-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_tank_raw_span_alter_tank_raw_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowmeter',
            name='high_limit',
            field=models.FloatField(default=90.0),
        ),
        migrations.AddField(
            model_name='flowmeter',
            name='low_limit',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='flowmeter',
            name='raw_span',
            field=models.FloatField(default=20000.0),
        ),
        migrations.AddField(
            model_name='flowmeter',
            name='raw_zero',
            field=models.FloatField(default=4000.0),
        ),
    ]
