# Generated by Django 6.0.6 on 2026-07-18 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_flowmeter_high_limit_flowmeter_low_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='flow_meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='core.flowmeter'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='core.tank'),
        ),
    ]
