# Generated by Django 6.0.6 on 2026-07-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alarm_flow_meter_alter_alarm_tank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowmeter',
            name='high_limit',
        ),
        migrations.RemoveField(
            model_name='flowmeter',
            name='low_limit',
        ),
        migrations.RemoveField(
            model_name='flowmeter',
            name='raw_span',
        ),
        migrations.RemoveField(
            model_name='flowmeter',
            name='raw_zero',
        ),
    ]
