# Generated by Django 6.0.6 on 2026-07-19 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_flowmeter_high_limit_flowmeter_low_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='flow_meter',
        ),
        migrations.RemoveField(
            model_name='flowmeter',
            name='high_limit',
        ),
        migrations.RemoveField(
            model_name='flowmeter',
            name='low_limit',
        ),
        migrations.AlterField(
            model_name='alarm',
            name='tank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='core.tank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tank',
            name='raw_span',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tank',
            name='raw_zero',
            field=models.FloatField(default=0.0),
        ),
    ]
