# Generated by Django 6.0.6 on 2026-07-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_alarm_flow_meter_remove_flowmeter_high_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowmeter',
            name='high_limit',
            field=models.FloatField(default=90.0),
        ),
        migrations.AddField(
            model_name='flowmeter',
            name='low_limit',
            field=models.FloatField(default=10.0),
        ),
    ]
