# Generated by Django 6.0.6 on 2026-07-19 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alarm_flow_meter_alter_alarm_tank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='flow_meter',
        ),
        migrations.AlterField(
            model_name='alarm',
            name='tank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='core.tank'),
            preserve_default=False,
        ),
    ]
