# Generated by Django 6.0.6 on 2026-07-19 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_alarm_flow_meter_alter_alarm_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='flow_meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='core.flowmeter'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='snooze_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='core.tank'),
        ),
    ]
