# Generated by Django 6.0.6 on 2026-07-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alarm_flow_meter_alarm_snooze_until_alter_alarm_tank'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The license key string', max_length=50, unique=True)),
                ('duration_days', models.IntegerField(default=365, help_text='Duration of the license in days')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this key has been activated')),
                ('activated_at', models.DateTimeField(blank=True, help_text='When the key was activated', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the license expires', null=True)),
            ],
        ),
    ]
