# Generated by Django 6.0.6 on 2026-07-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_licensekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowmeter',
            name='alarms_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='alarms_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
