# Generated by Django 6.0.6 on 2026-07-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_flowmeter_alarms_enabled_tank_alarms_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowmeter',
            name='alarms_enabled',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='alarms_enabled',
        ),
        migrations.AddField(
            model_name='flowmeter',
            name='alarm_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='alarm_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
