# Generated by Django 6.0.6 on 2026-07-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_flowmeter_alarms_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='raw_span',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='raw_zero',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='scaling',
        ),
        migrations.AlterField(
            model_name='tank',
            name='data_type',
            field=models.CharField(default='Float32', max_length=20),
        ),
    ]
