# Generated by Django 6.0.6 on 2026-07-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_tank_scaling_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='offset',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tank',
            name='raw_span',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tank',
            name='raw_zero',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tank',
            name='scaling',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='tank',
            name='data_type',
            field=models.CharField(default='UInt16', max_length=20),
        ),
    ]
