# Generated by Django 6.0.6 on 2026-07-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_tank_offset_tank_raw_span_tank_raw_zero_tank_scaling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='flow_rate_register',
            field=models.IntegerField(blank=True, default=40001, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='flow_unit',
            field=models.CharField(blank=True, default='L/min', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='total_unit',
            field=models.CharField(blank=True, default='Liters', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='total_volume_register',
            field=models.IntegerField(blank=True, default=40003, null=True),
        ),
        migrations.AddField(
            model_name='tankreading',
            name='flow_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tankreading',
            name='total_flow',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
