# Generated by Django 6.0.6 on 2026-07-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_tank_flow_rate_register_tank_flow_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmeter',
            name='total_unit',
            field=models.CharField(blank=True, default='Liters', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flowmeter',
            name='total_volume_register',
            field=models.IntegerField(blank=True, default=40003, null=True),
        ),
    ]
