# Generated by Django 6.0.6 on 2026-07-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_flowmeter_total_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowmeter',
            name='error_accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tank',
            name='error_accuracy',
            field=models.FloatField(default=0.0),
        ),
    ]
