# Generated by Django 6.0.6 on 2026-07-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_flowmeter_error_accuracy_tank_error_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankreading',
            name='raw_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
