# Generated by Django 6.0.6 on 2026-07-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_tankreading_raw_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tankreading',
            name='raw_value',
        ),
        migrations.AddField(
            model_name='tank',
            name='scanner_raw_span',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tank',
            name='scanner_raw_zero',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tankreading',
            name='raw_val',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
