# Generated by Django 6.0.6 on 2026-07-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_tankreading_raw_value_tank_scanner_raw_span_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tankreading',
            name='raw_val',
        ),
    ]
