# Generated by Django 6.0.6 on 2026-07-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_tankreading_raw_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankreading',
            name='raw_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
