# Generated by Django 6.0.6 on 2026-07-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_tankreading_raw_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='capacity_unit',
            field=models.CharField(blank=True, default='KL', max_length=15, null=True),
        ),
    ]
