# Generated by Django 6.0.6 on 2026-07-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_tank_capacity_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowmeter',
            name='flow_raw_span',
            field=models.FloatField(default=0.0, help_text='Raw register value at max flow'),
        ),
        migrations.AddField(
            model_name='flowmeter',
            name='flow_raw_zero',
            field=models.FloatField(default=0.0, help_text='Raw register value at 0 flow'),
        ),
    ]
