# Generated by Django 6.0.6 on 2026-07-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_flowmeter_flow_raw_span_flowmeter_flow_raw_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='flow_raw_span',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tank',
            name='flow_raw_zero',
            field=models.FloatField(default=0.0),
        ),
    ]
