# Generated by Django 6.0.6 on 2026-07-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_tank_flow_raw_span_tank_flow_raw_zero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowmeter',
            name='flow_raw_span',
        ),
        migrations.RemoveField(
            model_name='flowmeter',
            name='flow_raw_zero',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='flow_raw_span',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='flow_raw_zero',
        ),
        migrations.AddField(
            model_name='flowmeter',
            name='calibrated_span',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='flowmeter',
            name='scanner_raw_span',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flowmeter',
            name='scanner_raw_zero',
            field=models.FloatField(default=0.0),
        ),
    ]
