# Generated by Django 6.0.6 on 2026-07-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_flowmeter_flow_raw_span_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.CharField(blank=True, help_text='The license key string. Leave blank to auto-generate a secure 24-character key.', max_length=50, unique=True),
        ),
    ]
