from django.urls import path
from . import views

urlpatterns = [
    path("", views.splash_view, name="splash"),
    path("welcome/", views.welcome_view, name="welcome"),
    path("renew-license/", views.renew_license_view, name="renew_license"),
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("trend-chart/", views.trend_chart_view, name="trend_chart"),
    path("alarms/", views.alarms_view, name="alarms"),
    path("reports/", views.reports_view, name="reports"),
    path("data-log/", views.data_log_view, name="data_log"),
    path("settings/", views.settings_view, name="settings"),
    path("events/", views.events_view, name="events"),
    path("users/", views.users_list_view, name="users_list"),
    path("users/add/", views.users_add_view, name="users_add"),
    path("users/<int:pk>/edit/", views.users_edit_view, name="users_edit"),
    path("users/<int:pk>/delete/", views.users_delete_view, name="users_delete"),
    path("export/trend/", views.export_trend_csv, name="export_trend"),
    path("export/alarms/", views.export_alarms_csv, name="export_alarms"),
    path("export/reports/", views.export_reports_csv, name="export_reports"),
    path("export/datalog/", views.export_datalog_csv, name="export_datalog"),
    path("export/events/", views.export_events_csv, name="export_events"),
    path("api/tanks/", views.api_tank_data, name="api_tank_data"),
    path("api/flow-meters/", views.api_flow_meter_data, name="api_flow_meter_data"),
    path("api/historical-data/", views.api_historical_data, name="api_historical_data"),
    path("settings/add-tank/", views.settings_add_tank_view, name="settings_add_tank"),
    path("settings/delete-tank/<str:tank_id>/", views.settings_delete_tank_view, name="settings_delete_tank"),
    path("settings/update-capacities/", views.settings_update_capacities_view, name="settings_update_capacities"),
    path("settings/add-flow-meter/", views.settings_add_flow_meter_view, name="settings_add_flow_meter"),
    path("settings/delete-flow-meter/<str:meter_id>/", views.settings_delete_flow_meter_view, name="settings_delete_flow_meter"),
    path("settings/list-com-ports/", views.settings_list_com_ports_view, name="settings_list_com_ports"),
    path("settings/save-connection/", views.settings_save_connection_view, name="settings_save_connection"),
    path("settings/test-connection/", views.settings_test_connection_view, name="settings_test_connection"),
    path("settings/save-simulated-register/", views.settings_save_simulated_register_view, name="settings_save_simulated_register"),
    path("settings/scan-ports/", views.settings_auto_port_scan_view, name="settings_scan_ports"),
    path("settings/scan-slaves/", views.settings_auto_slave_scan_view, name="settings_scan_slaves"),
    path("settings/scan-registers/", views.settings_register_scan_view, name="settings_scan_registers"),
    path("api/diagnostics/", views.api_diagnostics_view, name="api_diagnostics"),
    path("alarms/set-limits/", views.set_alarm_limits_view, name="set_alarm_limits"),
    path("settings/toggle-alarm/", views.toggle_device_alarm_view, name="settings_toggle_alarm"),
    path("api/active-alarms/", views.api_active_alarms, name="api_active_alarms"),
    path("api/acknowledge-alarm/", views.api_acknowledge_alarm, name="api_acknowledge_alarm"),
    path("api/alarm-detail/<int:alarm_id>/", views.api_alarm_detail, name="api_alarm_detail"),
]

